[package]
version = "1.0.0"
description = "JSON-RPC 2.0 implementation"
name = "jsonrpc"

[lib]
path = "lib.rs"

# [workspace]

[dependencies]
jsonrpc-core = { path = "core" }
jsonrpc-http-server = { path = "http" }
# jsonrpc-ipc-server = { path = "ipc" }
jsonrpc-tcp-server = { path = "tcp" }
# jsonrpc-macros= { path = "macros" }

