[package]
name = "jsonrpc-stdio-server"
description = "STDIN/STDOUT server for JSON-RPC"
version = "0.1.0"
authors = ["cmichi <mich@elmueller.net>"]
license = "MIT"
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
documentation = "https://paritytech.github.io/jsonrpc/jsonrpc_stdio_server/index.html"

[dependencies]
futures = "0.1.23"
jsonrpc-core = { version = "9.0", path = "../core" }
log = "0.4"
tokio = "0.1.7"
tokio-codec = "0.1.0"
tokio-io = "0.1.7"
tokio-stdin-stdout = "0.1.4"

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.5"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
