[package]
name = "jsonrpc-derive"
version = "9.0.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "^0.15.22", features = ["full", "extra-traits", "visit", "fold"] }
proc-macro2 = "0.4"
quote = "0.6"

[dev-dependencies]
jsonrpc-core = { version = "9.0", path = "../core" }
jsonrpc-pubsub = { version = "9.0", path = "../pubsub" }
jsonrpc-tcp-server = { version = "9.0", path = "../tcp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
