[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Rust http server using JSONRPC 2.0."
documentation = "https://docs.rs/jsonrpc-http-server/"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "server"]
license = "MIT"
name = "jsonrpc-http-server"
repository = "https://github.com/paritytech/jsonrpc"
version = "14.0.1"

[dependencies]
hyper = "0.12"
jsonrpc-core = { version = "14.0", path = "../core" }
jsonrpc-server-utils = { version = "14.0", path = "../server-utils" }
log = "0.4"
net2 = "0.2"
unicase = "2.0"
parking_lot = "0.9.0"
[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
