[package]
description = "Rust http server using JSONRPC 2.0."
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
license = "MIT"
name = "jsonrpc-http-server"
version = "7.0.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "server"]
documentation = "https://ethcore.github.io/jsonrpc/jsonrpc_http_server/index.html"

[dependencies]
log = "0.3"
futures = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-minihttp = { git = "https://github.com/tomusdrw/tokio-minihttp" }
jsonrpc-core = { version = "5.1", path = "../core" }
unicase = "1.3"

[features]
default = ["jsonrpc-core/reactor"]
