[package]
name = "jsonrpc-ws-server"
description = "WebSockets server for JSON-RPC"
version = "10.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
documentation = "https://paritytech.github.io/jsonrpc/json_ws_server/index.html"

[dependencies]
error-chain = "0.12"
jsonrpc-core = { version = "10.0", path = "../core" }
jsonrpc-server-utils = { version = "10.0", path = "../server-utils" }
log = "0.4"
parking_lot = "0.7"
slab = "0.4"
parity-ws = "0.8"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
