[package]
name = "jsonrpc-tcp-server"
description = "TCP/IP server for JSON-RPC"
version = "9.0.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "MIT"
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
documentation = "https://paritytech.github.io/jsonrpc/jsonrpc_tcp_server/index.html"

[dependencies]
log = "0.4"
parking_lot = "0.6"
tokio-service = "0.1"
jsonrpc-core = { version = "9.0", path = "../core" }
jsonrpc-server-utils = { version = "9.0", path = "../server-utils" }

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.5"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
