[package]
name = "jsonrpc-tcp-server"
description = "TCP/IP server for JSON-RPC"
version = "6.0.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "MIT"
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
documentation = "https://ethcore.github.io/jsonrpc/json_tcp_server/index.html"

[dependencies]
jsonrpc-core = { version = "6.0", path = "../core" }
log = "0.3"
serde_json = "0.9"
rand = "0.3"
tokio-core = "0.1"
tokio-service = "0.1"
# tokio-proto = "0.1"
# Referencing git version to solve build issues.
tokio-proto = { git = "https://github.com/tomusdrw/tokio-proto" }

[dev-dependencies]
lazy_static = "0.2"
env_logger = "0.4"

[features]
default = ["jsonrpc-core/reactor"]
