[package]
name = "jsonrpc-tcp-server"
version = "1.0.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
documentation = "https://ethcore.github.io/jsonrpc/json_tcp_server/index.html"

[dependencies]
jsonrpc-core = { version = "5.0", path = "../core" }
log = "0.3"
env_logger = "0.3"
lazy_static = "0.2"
serde_json = "0.8"
rand = "0.3"
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"

[features]
default = ["jsonrpc-core/reactor"]
