[package]
name = "jsonrpc-ipc-server"
version = "1.2.4"
authors = ["Nikolay Volf <nikvolf@gmail.com>"]
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
documentation = "https://ethcore.github.io/jsonrpc/json_ipc_server/index.html"

[dependencies]
jsonrpc-core = { version = "5.0", path = "../core" }
mio = "0.5"
slab   = "0.1.0"
bytes  = "0.3.0"
miow = "0.1"
log = "0.3"
env_logger = "0.3"
lazy_static = "0.2"
rand = "0.3"

[features]
default = ["jsonrpc-core/reactor"]
