[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Publish-Subscribe extension for jsonrpc."
documentation = "https://docs.rs/jsonrpc-pubsub/"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
license = "MIT"
name = "jsonrpc-pubsub"
repository = "https://github.com/paritytech/jsonrpc"
version = "13.0.0"

[dependencies]
log = "0.4"
parking_lot = "0.8"
jsonrpc-core = { version = "13.0", path = "../core" }
serde = "1.0"

[dev-dependencies]
jsonrpc-tcp-server = { version = "13.0", path = "../tcp" }

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
